[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rio_hw"
authors = [{ name = "rio developers", email = "etaoxing@users.noreply.github.com" }]
description = "A real-time control library for cross-embodiment robot manipulation"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]
dynamic = ["version", "readme"]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
    "opencv-python",
    "scipy",  # spatial transforms
    "spatialmath-python",  # so3, se3 math
    "threadpoolctl",  # thread limiting
    "tyro",  # dataclass cfg command-line interface
    "prettytable",  # terminal tables
]

[tool.uv]
# pip install atomics --no-binary=atomics --no-cache --force-reinstall
# https://github.com/doodspav/atomics/issues/5
no-binary-package = ["atomics"]

[project.optional-dependencies]
dev = [
    "ipdb",
    "pre-commit",
    "pytest",
    "pytest-xdist",
    "ruff",
    "ty",
    "typos",
]
serializers = [
    "cloudpickle",
    "msgpack_numpy",
    "ormsgpack",
]
# --- nodes ---
cameras = [
    "pyrealsense2==2.54.2.5684; sys_platform != 'darwin'",  # realsense
    "pyrealsense2-macosx==2.54.2; sys_platform == 'darwin'",  # realsense
    "record3d",  # record3d
    "cv2_enumerate_cameras",  # uvc
    # "pyzed",  # zed
]
interfaces = [
    "avp_stream",
    "evdev; sys_platform != 'darwin'",  # gamepad
    "gello @ https://github.com/etaoxing/gello_software/archive/68530625dfbea9fefe8add23fd351ec7c0cb8516.tar.gz",
    "pynput", # keyboard
    "oculus_reader @ https://github.com/etaoxing/oculus_reader/archive/2c837e3960cc108b28e54388b1da8323ad3f3ac6.tar.gz",
    "spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz", # spacemouse
]
middlewares = [
    "portal",
    "atomics",  # shm, shmf
    "eclipse-zenoh",  # zenoh
    "zerorpc",
    "pyzmq",  # zmq
]
robots = [
    # "panda_py; sys_platform != 'darwin'",  # franka
    # "polymetis; sys_platform != 'darwin'",  # franka
    "pylibfranka; sys_platform != 'darwin'",  # franka
    "dynamixel_sdk",  # leap_hand
    "pyrobotiqgripper",  # robotiq gripper
    "ur-rtde==1.5.6; sys_platform != 'darwin'",  # ur
    "xarm-python-sdk==1.17.0",  # xarm
]

[tool.setuptools.packages.find]
include = ["rio_hw*"]

[tool.setuptools.dynamic]
version = { file = ["VERSION"] }
readme = { file = ["README.md"], content-type = "text/markdown" }

[tool.ruff]
cache-dir = ".cache/ruff"
line-length = 128
indent-width = 4
extend-exclude = [
    "third_party/",
]
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "I",   # isort
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "NPY", # NumPy-specific rules
    "PLC", # pylint convention
    "PLE", # pylint error
    "PLW", # pylint warning
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
]
ignore = [
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "E731",  # Do not assign a lambda expression, use a def
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"examples/*" = ["PLC0415"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = [
    "rio_hw/_tests",
]

[tool.typos]
files.extend-exclude = ["*.urdf", "*.usd", "*.usda", "*.mjcf"]

[tool.typos.default.extend-words]
UDID = "UDID"

[tool.typos.default.extend-identifiers]
SharedNDArray = "SharedNDArray"
